[2025-04-17T07:45:15.338+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-17T07:45:15.376+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.run_dbt_trusted scheduled__2025-04-15T07:36:00+00:00 [queued]>
[2025-04-17T07:45:15.392+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_raw_data_pipeline.run_dbt_trusted scheduled__2025-04-15T07:36:00+00:00 [queued]>
[2025-04-17T07:45:15.392+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-04-17T07:45:15.421+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): run_dbt_trusted> on 2025-04-15 07:36:00+00:00
[2025-04-17T07:45:15.428+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=420) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-17T07:45:15.431+0000] {standard_task_runner.py:72} INFO - Started process 424 to run task
[2025-04-17T07:45:15.430+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_raw_data_pipeline', 'run_dbt_trusted', 'scheduled__2025-04-15T07:36:00+00:00', '--job-id', '242', '--raw', '--subdir', 'DAGS_FOLDER/lead_data_pipeline.py', '--cfg-path', '/tmp/tmpkvmga8v1']
[2025-04-17T07:45:15.432+0000] {standard_task_runner.py:105} INFO - Job 242: Subtask run_dbt_trusted
[2025-04-17T07:45:15.490+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_raw_data_pipeline.run_dbt_trusted scheduled__2025-04-15T07:36:00+00:00 [running]> on host c0ac39583bd8
[2025-04-17T07:45:15.604+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_raw_data_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_trusted' AIRFLOW_CTX_EXECUTION_DATE='2025-04-15T07:36:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-15T07:36:00+00:00'
[2025-04-17T07:45:15.606+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-17T07:45:15.629+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-17T07:45:15.633+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'set -x; cd /opt/***/dbt && dbt run --select tag:trusted']
[2025-04-17T07:45:15.648+0000] {subprocess.py:86} INFO - Output:
[2025-04-17T07:45:15.651+0000] {subprocess.py:93} INFO - + cd /opt/***/dbt
[2025-04-17T07:45:15.652+0000] {subprocess.py:93} INFO - + dbt run --select tag:trusted
[2025-04-17T07:45:18.206+0000] {subprocess.py:93} INFO - [0m07:45:18  Running with dbt=1.8.0
[2025-04-17T07:45:18.527+0000] {subprocess.py:93} INFO - [0m07:45:18  Registered adapter: postgres=1.8.2
[2025-04-17T07:45:18.999+0000] {subprocess.py:93} INFO - [0m07:45:18  Found 9 models, 10 sources, 428 macros
[2025-04-17T07:45:19.004+0000] {subprocess.py:93} INFO - [0m07:45:19
[2025-04-17T07:45:19.162+0000] {subprocess.py:93} INFO - [0m07:45:19  Concurrency: 1 threads (target='dev')
[2025-04-17T07:45:19.163+0000] {subprocess.py:93} INFO - [0m07:45:19
[2025-04-17T07:45:19.177+0000] {subprocess.py:93} INFO - [0m07:45:19  1 of 4 START sql table model lead_trusted.non_pii_data ......................... [RUN]
